In [1]:
#naming conventions in Python
a = 4
b = 5

4

In [ ]:
'''
Comments are ways we tell ourselves and others what the code does

'''

In [2]:
c = 7
d = 7.0

type(d)

float

In [3]:
e = 'hello'
f = "My name is mike"

type(f)

str

In [ ]:
#Rules of naming

'''
Single variable names are not good coding style
you cannot start a variable with a number
'''
filterorder = 18
user_name =   'mike'
param4model1A = 43.58745

In [4]:
#to find all the variable names created

%whos

Variable   Type     Data/Info
-----------------------------
a          int      4
c          int      7
d          float    7.0
e          str      hello
f          str      My name is mike


In [ ]:
### Multiple assignment
varA = 3
varB = 'test'

varA,varB = 3,'test'


In [6]:
#can we redifine the variable?
varA = 8.00
type(varA)

float

In [9]:
### Math and Printing

x = 7
y = 4.3
z = 0

c = y + 3.5*x - 7
c

21.8

In [10]:
4/3 #here the slash is for dividion
4 \ #here the slash is for continuing on another line
  + 3

7

In [11]:
3**2
9**1/2 ## the intended is 9**(1/2)

4.5

In [14]:
firstName = 'mike'
lastName =  'cohen'

#overloading
fullName = firstName + " " + lastName
fullName 
fullName*3

'mike cohenmike cohenmike cohen'

In [16]:
print(str(x) + ' + ' + str(y) + ' = ' + str(x+y))

7 + 4.3 = 11.3


In [17]:
ans = input('give me a number: ')


give me a number:  5


In [18]:
ans + 5

TypeError: can only concatenate str (not "int") to str

In [19]:
ans = float(input('Give me a number: '))

Give me a number:  68


In [20]:
ans*2

136.0

In [ ]:
#exercise 
#test pythagorean theorem


#get two inputs from the user
# side 'a'
#side 'b'

# - compute and print out the length of side c!



In [24]:
sideA = float(input('Length of side a: '))
sideB = float(input ('Length of side b '))
  
sideC = (sideA**2 + sideB**2)**(1/2)

print('The length of side C is ' + str(sideC))

Length of side a:  3
Length of side b  4


The length of side C is 5.0


List(1 and 2)

In [25]:
#list 
alist = [ 4,5,2,0,3, 8 ] #there are six elements in this list
strlist = [ 'hi', 'my', 'is', 'mike']

mixlist = [ 8, 5.01, 'test', 50.1] #Antything can go inside a list provided that it is separated by comas
mixlist

listlist = [ 1,2,3, 'hi', 'bye', [.5, 1/4, 'i', 5,6,3]]

[8, 5.01, 'test', 50.1]

In [28]:
listlist = [
            1, #the pretty good stuff with this stuff is that we can write comments
            2,
            3, 
            'hi', 
            'bye', 
            [.5, 1/4, 'i',],
            5,
            6,
            3]

In [31]:
## working with list

#i want to know if 4 is in the list
5 in listlist

True

In [32]:
# concatenating two lists

alist + listlist

[4, 5, 2, 0, 3, 1, 2, 3, 'hi', 'bye', [0.5, 0.25, 'i'], 5, 6, 3]

In [33]:
alist*3

[4, 5, 2, 0, 3, 4, 5, 2, 0, 3, 4, 5, 2, 0, 3]

In [34]:
#method - a method is a function that acts on a particular type of variable
alist.append(-100)
print(alist)

[4, 5, 2, 0, 3, -100]


In [36]:
alist.sort()
alist

[-100, 0, 2, 3, 4, 5]

In [37]:
# execise
#use a list method to find the number of '-100' in alist

alist.count(-100)

1

A list 2 of 2


In [39]:
lst = [1,2,3,4,5]

print(lst)
lst.append(7) #this is a method to add an element in the list
lst

[1, 2, 3, 4, 5]


[1, 2, 3, 4, 5, 7]

In [40]:
lst.insert(2,8)  #2 corresonds to the position and 8 corresponds ot the element that occupies the positin
lst

[1, 2, 8, 3, 4, 5, 7]

In [41]:
lst.insert(4, 'qwerty')
lst

[1, 2, 8, 3, 'qwerty', 4, 5, 7]

In [43]:
lst.remove(4)
lst.remove(lst[1])
lst

[1, 8, 3, 'qwerty', 4, 5, 7]

In [ ]:
#exercise
#remove the string 'qwerty' and then sort





Tuple

In [44]:
atuple = (3, 'asdf', 4.3)

atuple = 3, 'asdf', 4.3

In [46]:
atuple*3

(3, 'asdf', 4.3, 3, 'asdf', 4.3, 3, 'asdf', 4.3)

In [ ]:
# difference between a tuple and a list
# A list is nutable 
# A list is immutable



In [47]:
print(alist)
alist[0] = 13.13
print(alist)

[-100, 0, 2, 3, 4, 5]
[13.13, 0, 2, 3, 4, 5]


In [48]:
# test for immutability 
print(atuple[0])
atuple[0] = 13.12
print(atuple)

3


TypeError: 'tuple' object does not support item assignment


Boolean  #used in logical programming

In [ ]:
b = True
f = False

In [50]:
4 == 4.1

False

In [51]:
test = 4 == 48

print(test)

False


In [52]:
3<=9
7 != 9 #this means 7 not equal to

True

In [54]:
# conjunctivbe comparision

x =10
x>5 and x<15
x>5 and y>15 and (x+y)<50

False

In [55]:
x > 5 or y<15

True

In [56]:
bool(-34223.99)

True

In [57]:
bool('eel')

True

In [58]:
bool(' ')

True

In [ ]:
# Excrise

#input from the user 3 number: a,b,c
#check wether c**2 = a**2 + b**2
#print out the result


#kist []
# Atuple()
#dictionaries


D = dict()


In [61]:
import keras

ModuleNotFoundError: No module named 'keras'

In [1]:
# dictionaries : key/value pairs
D =dict()

D
# [] Lists
# () tuples
# {} dictionaries



{}

In [3]:
D['name'] = 'Mike'
D['ageRnage'] = [20,50]

D

{'name': 'Mike', 'ageRnage': [20, 50]}

In [ ]:
'''
Dictionaries are not ordered, list are ordered, tuples are ordered but dictionaries are not ordered
'''

E = {'name': 'Mike', 'ageRnage': [20, 50], 'FavColor' : 'purple'}


Indexing: indexing is what allows us to access particular elements of a list or a tuple or any data type
that is an ordered list of item

indexing means to call a specific index or element of an ordered collection of information



In [56]:
alist = [4,6,2,-6,'qwerty',10,0.1]
#alist[4] # this is for an index 4   ####We use square bracket to creat index

In [3]:
alist[0]

int

In [57]:
'''
Index must be integers and not float
'''
idx = 4
alist(4)


TypeError: 'list' object is not callable

In [14]:
## If we want to access the last element 
#alist[len(alist)]


alist[len(alist)-1]

alist[-1]

0.1

In [20]:
## how to access embedded list
blist = [4,2,-6,[10,20,30,4],10,0.1]

exa = blist[3]

exa[2]

30

In [21]:
blist[3][2]

30

In [23]:
#Exercise

embeddiclist = [4, 'hi', [5,4,3],'yo',{'squirrel': 'cute', 'penguin': 'yummy'}]

embeddiclist[4]['penguin']

'yummy'

Slicing: Slicing is a procedure on lists and tuples and numpy arrays of matricies that allow you 
to multiple elements at the same time.



    

In [27]:
a= list(range(5,11))  #this produces a range of values from 5 to 11
a[2]  # this gives the index no 2 which is third element in the list which is 7


## so lets say you want all the elements from o to the 3rd index

a[0:2]  #this returns from 0 up until 2 but exclusing 2

[5, 6]

In [28]:
a[0:3] #if we want to access all the elements in the list from index 0 to 3 but not including 3

[5, 6, 7]

In [29]:
## so if you want to slice from 3 up until the end

a[3:]

[8, 9, 10]

In [33]:
a= list(range(5,11)) 
a

[5, 6, 7, 8, 9, 10]

In [36]:

a[::2]  ## this line of code reduces the list by two till the end

[5, 7, 9]

In [38]:
## start from index 1 and count two times
a[1::2] ### this skips by two but it start from index 1


[6, 8, 10]

In [39]:
a[1::4]  ## start from index 1 and count 4 times. ## when counting include the begnning index

[6, 10]

In [42]:
start = 0
stop = 5
skip = 2

a[start:stop:skip]

[5, 7, 9]

In [43]:
## reverse a list
a[::-1]

[10, 9, 8, 7, 6, 5]

In [4]:
#exercise
text = '345dfyug ecin a si ekim 93855d'
#use slicing to write 'mike is a nice guy' from the list 'text'

start = -8
stop = 4
skip = -1
text[start:stop:skip]

'mike is a nice guy'

function

In [5]:
## sum function
sum([10,10,30])

50

In [6]:
var = [20,20,30]
sum(var)

70

In [8]:
var =[20,20,30, [1,2,3]]
sum(sum)

In [9]:
var  =[20,20,30,50.55]
sum(var)

120.55

In [10]:
var = [20,20,50.55]
output = sum(var)

print('The sum is ' + str(output))

The sum is 90.55


In [ ]:
output = sum(var1, var2) #sum function can take multiple inputs just as variable.

In [11]:
#Exercise: compute the arithmetic average of the var
sum(var) / len(var)

30.183333333333334

### NUMPY

In [ ]:
## There are tons of functions that does not come with the built in functions
### so these functions are in libraries 

##Introducing you to libraries which is collection of functions

In [13]:
import numpy as np #everything that is accessible in numpy can be accessible in np.

In [17]:
numbers = [1,2,3,4]
np.mean(numbers)

2.5

In [ ]:
'''
This calls a function that gives linearly spaced numbers from 1 to 7 and there is going to be 5 of them
'''
np.linspace(1,7,5)

In [14]:
np.linspace(1,7,5)  
### Observations: the result of the operation is neither a list, tuple or anyother object you know
### The result of the operation is call an ARRAY.

array([1. , 2.5, 4. , 5.5, 7. ])

In [15]:
x = np.linspace(1,7,5) 
type(x) ## observe that the type of x is an array
### The nd means an n dimensional array. the type 'numpy.ndarray allows us to create multidimensional
## arrays such as matricies and tensors and so on'

numpy.ndarray

In [18]:
type(numbers)

list

In [19]:
'''
We can convert from list to numpy
'''

numbers_np = np.array(numbers)
print(type(numbers))
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [22]:
## Remember that there are methods you can call on a list

## Example: numbers.append     numbers.sort



### there are methods that you can apply on numpy
numbers_np.min()
np.min(numbers_np)

1

In [23]:
np.max(numbers)  #there are methods on numpy that can be called on a list 
## remember that object numbers is a list
##so numpy is gonna treat it as numbers

4

In [24]:
np.mean(numbers)

2.5

In [25]:
#import numpy as np
from numpy import mean as m  ## the instruction here imports only mean from all the numpy functions
numbers = [1,2,3,4,5,6]
m(numbers)

3.5

In [ ]:
## in-place
## out-of-place operations

In [26]:
n = [4,3,5,6,7,8,4]


print(n) #this prints the original list object
n.sort() #this sorts the list object
print(n) #this prints the sorted list object

[4, 3, 5, 6, 7, 8, 4]
[3, 4, 4, 5, 6, 7, 8]


In [27]:
n = [4,3,5,6,7,8,4]
nn = np.array(n)

print(nn) ## the object here is a numpy array 
nn.sort() ## this is a method for list being called on numpy
print(nn) ##do you think the result will be the same

[4 3 5 6 7 8 4]
[3 4 4 5 6 7 8]


In [28]:
n = [4,3,5,6,7,8,4]
nn = np.array(n)

print(nn)  
np.sort(nn) ## what will this result be??
print(nn)

[4 3 5 6 7 8 4]
[4 3 5 6 7 8 4]


In [ ]:
np.sort(nn) ### this is not an inplace operation



In [29]:
n = [4,3,5,6,7,8,4]
nn = np.array(n)

print(nn)  
nns = np.sort(nn) 
print(nns)

[4 3 5 6 7 8 4]
[3 4 4 5 6 7 8]


#PANDAS

In [ ]:
'''
There are many libraries in the python universe. 

What does pandas allow us to do:

Pandas is a library that gives us access to functions that are specifically written for datasets

Not all datasets but datasets can be organized like obervation by features.

So think of datasets you find in excel spread sheets or any kinda spread sheet

Data can be put into two dimensions where the rows are the observations and the columns are the features


'''

In [42]:
import numpy as np ## people import it as a short cut np
import pandas as pd ## people typically import it as a shortcut as pd`

In [32]:
## creat randome data by generating random numbers using the numpy function

np.random.randn() #this returns a random number drawn from a gaussian distribution or normal distribution

## each time you run the code above, you will get different numbers 

-0.017010032048288767

In [33]:
np.random.randn(5) # this will generate a numpy array of five different random numbers.

array([-0.20073453,  0.69484597,  0.19994141, -1.55397357,  0.26086014])

In [34]:
np.random.randn(5,5) #this is a 5x5 random matrix

array([[ 4.13474260e-01, -1.16066898e+00,  1.53914082e+00,
        -1.24038012e+00,  6.27973423e-01],
       [-1.55455001e+00,  2.31033063e+00, -7.62344208e-01,
        -1.20791926e+00, -1.85527490e-03],
       [-3.54951744e-02, -1.15748266e+00,  3.56599378e-01,
         6.28050719e-01, -1.78983740e+00],
       [ 7.86332857e-01, -1.68623976e+00,  8.61537767e-02,
         1.10855575e+00,  1.48409928e+00],
       [ 5.83242695e-01,  1.55983224e+00, -1.05205246e+00,
        -6.89379269e-01,  1.33109256e+00]])

In [35]:
np.random.randn(100) ## this is a list of randomly generated 100 numbers 



array([ 0.24890801,  0.10657229,  0.8026537 ,  1.77648674, -1.1885133 ,
        0.63022061,  0.58095055,  0.86061498,  0.20621618,  0.44235374,
       -0.36180177,  0.3662677 , -0.63741917, -1.81532227, -0.10158608,
       -1.75017554,  0.43593099,  0.72579233, -0.3193957 , -0.79245234,
        0.15728002, -0.37937207, -1.69686776,  0.60630711,  0.72569675,
        1.36948634,  0.27761434,  0.64603846,  1.07743291, -1.68681232,
        1.10215588,  2.32596867,  1.18911814, -0.98272939,  0.07734117,
        0.39934711,  0.62235934, -1.0651898 , -0.11788135,  0.00898115,
        0.09787884, -0.52833337,  0.80559437,  0.39267641,  0.72121825,
       -1.16240836, -0.21585365,  0.45917095,  1.26876863,  2.00729883,
        0.03080648, -2.60714038, -0.36750597,  2.02824698, -0.84792345,
       -0.5863649 , -0.74561418, -0.15205741, -0.95677227,  0.82612715,
        0.49462134,  1.33398699,  0.7223017 , -1.42773226, -1.26367295,
       -1.7245491 , -0.88529989, -0.6008501 ,  0.59025267, -1.29

In [37]:
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100)>0  ##var2 is a bunch of trues or faulses 



array([False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True, False, False, False, False,  True,
        True, False,  True,  True, False, False,  True, False, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False])

In [39]:
#variable labels
labels = ['temperature(c)', 'ice cream']

'''
So this is a dataset that contains temperature in celcius and a boolean that indicates trues and false 
whether someone ate ice cream on that day corresponding to the temperature.
'''


'''
this is, a dataset of random numbers stored in two variables 

the dataset is distributed over three different variables 

There is are separate variables for each of the two features

And a third variable for the labels.
'''


'\nthis is a dataset of random numbers stored in two variables \n\nthe dataset is distributed over three different variables \n\nThere is are separate variables for each of the two features\n\nAnd a third variable for the labels.\n'

In [40]:
## put all the variable into a dictionary 

D = {labels[0]:var1, labels[1]:var2}

D

{'temperature(c)': array([30.78740447, 25.98340859, 19.72285275, 16.79128235, 16.08803053,
        13.955895  , 15.17403882, 28.35183665, 13.02131213, 24.2651825 ,
        15.35135002, 19.59260586, 15.42809137, 23.45084437, 18.78642679,
        21.00455033, 22.52701278, 17.50083073, 20.26499081, 29.29554985,
        16.75200987, 22.55596842, 18.52348524, 15.20369929, 11.35074203,
        19.5651807 , 22.85151364, 24.18267005, 21.56575854, 22.99071434,
        24.42048158, 17.35765849, 27.22668077, 14.85144736, 15.08801215,
        24.5393739 , 18.1264627 , 15.87951927, 14.38399778, 20.9677138 ,
        13.79411931, 17.4167624 , 22.72815601, 13.59243235, 17.95471688,
         8.49837177, 26.00058215, 21.63381131, 16.80251393, 20.12097443,
        10.51711495, 19.16231384, 19.47456547, 23.77740583, 19.29307735,
        22.518064  , 16.87270386, 11.47318029, 17.63355241, 18.26063754,
        13.37592708, 25.40560479, 15.23166102, 21.46238432, 24.6488524 ,
        17.45588208, 10.43554489,

In [43]:
## import the dictionary into a pandas dataframe

df = pd.DataFrame(data=D) ##python is case sensistive so ensure that the DataFrame is not dataframe

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df

temperature(c)  ice cream
0        30.787404      False
1        25.983409      False
2        19.722853      False
3        16.791282       True
4        16.088031      False
..             ...        ...
95       22.503624       True
96       15.815427      False
97       21.169828       True
98       14.067595       True
99       17.255175      False

[100 rows x 2 columns]

In [47]:
df.head() # this is an object of the first five headers in the dataset

temperature(c)  ice cream
0       30.787404      False
1       25.983409      False
2       19.722853      False
3       16.791282       True
4       16.088031      False

In [48]:
df.count() #this returns the number of observations that we have for each of the columns

temperature(c)    100
ice cream         100
dtype: int64

In [49]:
df.mean()  ## notice that the ice cream column is a float point but python has converted the falses to 
## zero and the trues to one. 

####0.5 means that half of the labels are false and half of the labels are true

temperature(c)    19.298219
ice cream          0.550000
dtype: float64

In [ ]:
## Exercise'

##Create a pandas dataframe with:

##integers going from 0 to 10, their square, and their log

In [ ]:
### There is no one single correct way to get something done in python or programming in general


In [53]:
nums = np.array(range(11))

df = pd.DataFrame({'nums':nums, 'square': nums**2, 'log': np.log(nums)})

### the instruction below is a warning message

<ipython-input-53-3a812c4c3cfb>:3: RuntimeWarning: divide by zero encountered in log
  df = pd.DataFrame({'nums':nums, 'square': nums**2, 'log': np.log(nums)})


In [ ]:
## warning:we think that you might possibly have done something wrong
## error: you did something wrong

In [54]:
df

nums  square       log
0      0       0      -inf
1      1       1  0.000000
2      2       4  0.693147
3      3       9  1.098612
4      4      16  1.386294
5      5      25  1.609438
6      6      36  1.791759
7      7      49  1.945910
8      8      64  2.079442
9      9      81  2.197225
10    10     100  2.302585