In [8]:
import numpy as np

array = np.random.randn(5,4)
array

array([[ 7.66554826e-01,  3.71070420e-01,  1.85317817e-01,
        -5.73630200e-01],
       [-1.49231073e+00, -1.85584856e+00, -4.21963456e-01,
        -1.02354966e+00],
       [-8.64968547e-04, -4.44702746e-01, -5.71113820e-01,
        -4.78592665e-01],
       [-7.68800582e-02,  2.59229698e-01,  1.40422782e-01,
         4.59137488e-02],
       [-4.85130994e-01,  5.94355342e-02,  5.52520219e-01,
         2.12341236e-01]])

In [9]:
print(array.mean())

-0.2415890785088751


In [11]:
array.sum()

-4.831781570177502

In [14]:
array.mean(axis=1)

array([ 0.18732822, -1.1984181 , -0.37381855,  0.09217154,  0.0847915 ])

In [15]:
array2 = np.array([0,1,2,3,4,5,6,7])

print(array2)
array2.cumsum()

[0 1 2 3 4 5 6 7]


array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [21]:
array3 = np.random.randn(6)
array3

array([-0.04242   , -0.50992087,  1.60820101, -1.20272108, -0.06638145,
       -0.04934821])

In [18]:
array3.sort()


None
